name: 'Generate Documentation'
description: 'Generate Documentation from *.proto files.'
inputs:
  out-file:
    description: 'Documentation filename.'
    required: true
    default: 'doc'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.out-file }}
