name: 'Generate Documentation'
description: 'Generate Documentation from *.proto files.'
inputs:
  formats:
    description: 'Comma separated documentation formats.Available formats: html,md.'
    required: true
    default: 'html,md'
  filename:
    description: 'Documentation filename.'
    required: true
    default: 'index'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.formats }}
    - ${{ inputs.filename }}
